In [2]:
import h5py
import numpy as np

In [3]:
file_path = './ds_pre250408_ndetge8_pos250728/dataset.h5'
h5_file   = h5py.File(file_path)
h5_file.keys()

for k in h5_file.keys():
    print(f"{k}: shape={h5_file[k].shape}, dtype={h5_file[k].dtype}")

print()
print(h5_file.get("SNID")[:])
print()
print(h5_file.get("brightness")[:].shape)

SNID: shape=(259933,), dtype=object
brightness: shape=(259933, 200, 2), dtype=float32
class_name: shape=(259933,), dtype=object
e_brightness: shape=(259933, 200, 2), dtype=float32
extracted_feat_1024: shape=(259933, 191), dtype=float32
extracted_feat_128: shape=(259933, 191), dtype=float32
extracted_feat_16: shape=(259933, 191), dtype=float32
extracted_feat_256: shape=(259933, 191), dtype=float32
extracted_feat_32: shape=(259933, 191), dtype=float32
extracted_feat_512: shape=(259933, 191), dtype=float32
extracted_feat_64: shape=(259933, 191), dtype=float32
extracted_feat_8: shape=(259933, 191), dtype=float32
extracted_feat_None: shape=(259933, 191), dtype=float32
labels: shape=(259933,), dtype=int8
mask: shape=(259933, 200, 2), dtype=bool
mask_detection: shape=(259933, 200, 2), dtype=bool
mask_photometry: shape=(259933, 200, 2), dtype=bool
metadata_feat: shape=(259933, 8), dtype=float32
test: shape=(51682,), dtype=int64
time: shape=(259933, 200, 2), dtype=float32
time_detection: shape=

In [4]:
np.unique(h5_file['labels'][:])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20], dtype=int8)

In [5]:
np.unique(h5_file['class_name'][:])

array([b'AGN', b'Blazar', b'CEP', b'CV/Nova', b'DSCT', b'EA', b'EB/EW',
       b'LPV', b'Microlensing', b'Periodic-Other', b'QSO', b'RRLab',
       b'RRLc', b'RSCVn', b'SESN', b'SLSN', b'SNII', b'SNIIn', b'SNIa',
       b'TDE', b'YSO'], dtype=object)

In [6]:
file_path = './ds_pre250408_ndetge8_20folds_pos260202/dataset.h5'
h5_file   = h5py.File(file_path)
h5_file.keys()

for k in h5_file.keys():
    print(f"{k}: shape={h5_file[k].shape}, dtype={h5_file[k].dtype}")

print()
print(h5_file.get("SNID")[:])
print()
print(h5_file.get("brightness")[:].shape)

SNID: shape=(259933,), dtype=object
brightness: shape=(259933, 200, 2), dtype=float32
class_name: shape=(259933,), dtype=object
e_brightness: shape=(259933, 200, 2), dtype=float32
extracted_feat_1024: shape=(259933, 191), dtype=float32
extracted_feat_128: shape=(259933, 191), dtype=float32
extracted_feat_16: shape=(259933, 191), dtype=float32
extracted_feat_256: shape=(259933, 191), dtype=float32
extracted_feat_32: shape=(259933, 191), dtype=float32
extracted_feat_512: shape=(259933, 191), dtype=float32
extracted_feat_64: shape=(259933, 191), dtype=float32
extracted_feat_8: shape=(259933, 191), dtype=float32
extracted_feat_None: shape=(259933, 191), dtype=float32
labels: shape=(259933,), dtype=int8
mask: shape=(259933, 200, 2), dtype=bool
mask_detection: shape=(259933, 200, 2), dtype=bool
mask_photometry: shape=(259933, 200, 2), dtype=bool
metadata_feat: shape=(259933, 8), dtype=float32
test: shape=(51682,), dtype=int64
time: shape=(259933, 200, 2), dtype=float32
time_detection: shape=

In [7]:
np.unique(h5_file['labels'][:])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20], dtype=int8)

In [8]:
np.unique(h5_file['class_name'][:])

array([b'AGN', b'Blazar', b'CEP', b'CV/Nova', b'DSCT', b'EA', b'EB/EW',
       b'LPV', b'Microlensing', b'Periodic-Other', b'QSO', b'RRLab',
       b'RRLc', b'RSCVn', b'SESN', b'SLSN', b'SNII', b'SNIIn', b'SNIa',
       b'TDE', b'YSO'], dtype=object)

In [12]:
file_path = './ds_pre250408_ndetge8_sanchez_tax_20folds_pos260202/dataset.h5'
h5_file   = h5py.File(file_path)
h5_file.keys()

for k in h5_file.keys():
    print(f"{k}: shape={h5_file[k].shape}, dtype={h5_file[k].dtype}")

print()
print(h5_file.get("SNID")[:])
print()
print(h5_file.get("brightness")[:].shape)

SNID: shape=(259933,), dtype=object
brightness: shape=(259933, 200, 2), dtype=float32
class_name: shape=(259933,), dtype=object
e_brightness: shape=(259933, 200, 2), dtype=float32
extracted_feat_1024: shape=(259933, 191), dtype=float32
extracted_feat_128: shape=(259933, 191), dtype=float32
extracted_feat_16: shape=(259933, 191), dtype=float32
extracted_feat_256: shape=(259933, 191), dtype=float32
extracted_feat_32: shape=(259933, 191), dtype=float32
extracted_feat_512: shape=(259933, 191), dtype=float32
extracted_feat_64: shape=(259933, 191), dtype=float32
extracted_feat_8: shape=(259933, 191), dtype=float32
extracted_feat_None: shape=(259933, 191), dtype=float32
labels: shape=(259933,), dtype=int8
mask: shape=(259933, 200, 2), dtype=bool
mask_detection: shape=(259933, 200, 2), dtype=bool
mask_photometry: shape=(259933, 200, 2), dtype=bool
metadata_feat: shape=(259933, 8), dtype=float32
test: shape=(51682,), dtype=int64
time: shape=(259933, 200, 2), dtype=float32
time_detection: shape=

In [13]:
np.unique(h5_file['labels'][:])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int8)

In [14]:
np.unique(h5_file['class_name'][:])

array([b'AGN', b'Blazar', b'CEP', b'CV/Nova', b'DSCT', b'E', b'LPV',
       b'Others', b'Periodic-Other', b'QSO', b'RRL', b'SLSN', b'SNII',
       b'SNIa', b'SNIbc', b'YSO'], dtype=object)

In [ ]:
import h5py
import numpy as np

# Abrir archivo original
input_path = './ds_pre250408_ndetge8_sanchez_tax_20folds_pos260202/dataset.h5'
output_path = './dataset_window_0.h5'

with h5py.File(input_path, 'r') as h5_in:
    # Identificar índices que terminan en '_0'
    snids = h5_in['SNID'][:]
    mask_window0 = np.array([s.decode().endswith('_0') for s in snids])
    indices = np.where(mask_window0)[0]
    
    print(f"Seleccionados {len(indices)} objetos con ventana 0.")

    # Crear nuevo archivo .h5 con solo esos índices
    with h5py.File(output_path, 'w') as h5_out:
        for key in h5_in.keys():
            data = h5_in[key]
            if data.shape[0] == snids.shape[0]:
                # Dataset con la misma cantidad de objetos
                h5_out.create_dataset(key, data=data[indices])
            else:
                # Otros datasets como 'training_x', 'validation_x', etc., se omiten o copian completos si quieres
                print(f"Saltando key: {key} (shape: {data.shape})")
        
print("Nuevo archivo guardado en:", output_path)

In [5]:
import h5py
import numpy as np

input_path = './ds_pre250408_ndetge8_20folds_pos250514_float32/dataset.h5'
output_path = './dataset_window0.h5'

with h5py.File(input_path, 'r') as h5_in:
    # ⚡ Convertimos todos los SNID (bytes) a str de forma segura
    snid_raw = h5_in['SNID'][:]
    snids = np.array([s.decode('utf-8') for s in snid_raw])

    # Vectorizado: endswith '_0'
    mask_window0 = np.char.endswith(snids, '_0')
    indices = np.where(mask_window0)[0]

    print(f"✅ Seleccionados {len(indices)} objetos con ventana _0")

    # Creamos el nuevo archivo
    with h5py.File(output_path, 'w') as h5_out:
        for key in h5_in.keys():
            data = h5_in[key]
            if data.shape[0] == snid_raw.shape[0]:
                print(f"📦 Copiando: {key}")
                h5_out.create_dataset(key, data=data[indices], compression='gzip')
            else:
                print(f"⏭️ Saltando: {key} (shape: {data.shape})")

print("✅ Nuevo archivo guardado en:", output_path)


✅ Seleccionados 39483 objetos con ventana _0
📦 Copiando: SNID
📦 Copiando: brightness
📦 Copiando: class_name
📦 Copiando: e_brightness


KeyboardInterrupt: 

In [2]:
import h5py
import numpy as np
import pandas as pd

file_path = './ds_pre250408_ndetge8_20folds_pos250514_float32/dataset.h5'
h5_file = h5py.File(file_path, 'r')

# Decodificar SNIDs y filtrar por '_0'
snid = np.array([s.decode('utf-8') for s in h5_file['SNID'][:]])
mask_window0 = np.char.endswith(snid, '_0')
indices = np.where(mask_window0)[0]
print(f"Número de objetos con _0: {len(indices)}")

# Construir el all_data estilo create_dataset_h5py
all_data = {
    'oid': snid[indices],
    'time': h5_file['time'][indices],
    'brightness': h5_file['brightness'][indices],
    'e_brightness': h5_file['e_brightness'][indices],
    'mask': h5_file['mask'][indices],
    'time_detection': h5_file['time_detection'][indices],
    'mask_detection': h5_file['mask_detection'][indices],
    'time_photometry': h5_file['time_photometry'][indices],
    'mask_photometry': h5_file['mask_photometry'][indices],
    'label_int': h5_file['labels'][indices],
    'class_name': h5_file['class_name'][indices],
    # Si tienes metadata/features
    'metadata_feat': h5_file['metadata_feat'][indices],
}

for feat_name in h5_file.keys():
    if feat_name.startswith('extracted_feat_') and h5_file[feat_name].shape[0] == snid.shape[0]:
        all_data[feat_name] = h5_file[feat_name][indices]

output_path = './dataset_window0_fast.h5'
with h5py.File(output_path, 'w') as hf:
    hf.create_dataset("SNID", data=np.array(all_data["oid"], dtype='S'))  # string como bytes
    hf.create_dataset("time", data=all_data["time"].astype(np.float32))
    hf.create_dataset("brightness", data=all_data["brightness"].astype(np.float32))
    hf.create_dataset("e_brightness", data=all_data["e_brightness"].astype(np.float32))
    hf.create_dataset("mask", data=all_data["mask"].astype(bool))
    hf.create_dataset("time_detection", data=all_data["time_detection"].astype(np.float32))
    hf.create_dataset("mask_detection", data=all_data["mask_detection"].astype(bool))
    hf.create_dataset("time_photometry", data=all_data["time_photometry"].astype(np.float32))
    hf.create_dataset("mask_photometry", data=all_data["mask_photometry"].astype(bool))
    hf.create_dataset("labels", data=all_data["label_int"].astype(np.int8))
    hf.create_dataset("class_name", data=all_data["class_name"])  # tipo bytes

    # Agregar metadata y features si están
    if "metadata_feat" in all_data:
        hf.create_dataset("metadata_feat", data=all_data["metadata_feat"].astype(np.float32))

    for key in all_data:
        if key.startswith("extracted_feat_"):
            hf.create_dataset(key, data=all_data[key].astype(np.float32))

print("✅ Nuevo archivo rápido guardado:", output_path)

Número de objetos con _0: 39483


KeyboardInterrupt: 

In [ ]:
file_path = './ds_pre250408_ndetge8_20folds_pos250514_float32/dataset_window0_only.h5'
h5_file   = h5py.File(file_path)
h5_file.keys()

for k in h5_file.keys():
    print('{}: {}'.format(k, h5_file[k].shape))

print()
print(h5_file.get("SNID")[:])
print()
print(h5_file.get("brightness")[:].shape)

In [3]:
labels = h5_file.get("labels")[:]
labels

array([15, 15, 15, ...,  1,  1,  1], dtype=int8)

In [4]:
len(np.unique(labels))

21

In [5]:
unique_labels, counts = np.unique(labels, return_counts=True)
counts

array([18248, 33462,  7385, 16588, 28871,  8666,  3519,    49, 21293,
        8361, 27774, 27975, 11468, 23903,   356,  1866,   701,   423,
        3331,   180, 15514])

In [6]:
class_name = h5_file.get("class_name")[:]
class_name

array([b'SNII', b'SNII', b'SNII', ..., b'EB/EW', b'EB/EW', b'EB/EW'],
      dtype=object)

In [7]:
unique_labels, counts = np.unique(class_name, return_counts=True)
counts

array([18248,  7385, 16588,  8666,  8361, 27774, 33462, 28871,    49,
        3519, 21293, 27975, 23903, 11468,   356,  1866,   423,  3331,
         701,   180, 15514])

In [8]:
print(np.unique(h5_file.get("labels")[:]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [9]:
print(np.unique(h5_file.get("labels")[:]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [10]:
for k in h5_file.keys():
    print(f"{k}: shape={h5_file[k].shape}, dtype={h5_file[k].dtype}")

SNID: shape=(259933,), dtype=object
brightness: shape=(259933, 200, 2), dtype=float32
class_name: shape=(259933,), dtype=object
e_brightness: shape=(259933, 200, 2), dtype=float32
extracted_feat_1024: shape=(259933, 191), dtype=float32
extracted_feat_128: shape=(259933, 191), dtype=float32
extracted_feat_16: shape=(259933, 191), dtype=float32
extracted_feat_256: shape=(259933, 191), dtype=float32
extracted_feat_32: shape=(259933, 191), dtype=float32
extracted_feat_512: shape=(259933, 191), dtype=float32
extracted_feat_64: shape=(259933, 191), dtype=float32
extracted_feat_8: shape=(259933, 191), dtype=float32
extracted_feat_None: shape=(259933, 191), dtype=float32
labels: shape=(259933,), dtype=int8
mask: shape=(259933, 200, 2), dtype=bool
mask_detection: shape=(259933, 200, 2), dtype=bool
mask_photometry: shape=(259933, 200, 2), dtype=bool
metadata_feat: shape=(259933, 8), dtype=float32
test: shape=(51682,), dtype=int64
time: shape=(259933, 200, 2), dtype=float32
time_detection: shape=

In [19]:
file_path = './ds_pre250408_ndetge8_pos250522/dataset.h5'
h5_file   = h5py.File(file_path)
h5_file.keys()

for k in h5_file.keys():
    print('{}: {}'.format(k, h5_file[k].shape))

print()
print(h5_file.get("SNID")[:])
print()
print(h5_file.get("brightness")[:].shape)

SNID: (259933,)
brightness: (259933, 200, 2)
class_name: (259933,)
e_brightness: (259933, 200, 2)
extracted_feat_1024: (259933, 191)
extracted_feat_128: (259933, 191)
extracted_feat_16: (259933, 191)
extracted_feat_256: (259933, 191)
extracted_feat_32: (259933, 191)
extracted_feat_512: (259933, 191)
extracted_feat_64: (259933, 191)
extracted_feat_8: (259933, 191)
extracted_feat_None: (259933, 191)
labels: (259933,)
mask: (259933, 200, 2)
mask_detection: (259933, 200, 2)
mask_photometry: (259933, 200, 2)
metadata_feat: (259933, 8)
test: (51682,)
time: (259933, 200, 2)
time_detection: (259933, 200, 2)
time_photometry: (259933, 200, 2)
training_0: (166778,)
training_1: (166524,)
training_2: (166039,)
training_3: (166923,)
training_4: (166740,)
validation_0: (41473,)
validation_1: (41727,)
validation_2: (42212,)
validation_3: (41328,)
validation_4: (41511,)

[b'ZTF17aaaagyq_0' b'ZTF17aaaagyq_1' b'ZTF17aaaagyq_2' ...
 b'ZTF21aadkjfg_0' b'ZTF21aadkjfg_1' b'ZTF21aadoodn_0']

(259933, 200, 2)


In [20]:
for k in h5_file.keys():
    print(f"{k}: shape={h5_file[k].shape}, dtype={h5_file[k].dtype}")

SNID: shape=(259933,), dtype=object
brightness: shape=(259933, 200, 2), dtype=float32
class_name: shape=(259933,), dtype=object
e_brightness: shape=(259933, 200, 2), dtype=float32
extracted_feat_1024: shape=(259933, 191), dtype=float32
extracted_feat_128: shape=(259933, 191), dtype=float32
extracted_feat_16: shape=(259933, 191), dtype=float32
extracted_feat_256: shape=(259933, 191), dtype=float32
extracted_feat_32: shape=(259933, 191), dtype=float32
extracted_feat_512: shape=(259933, 191), dtype=float32
extracted_feat_64: shape=(259933, 191), dtype=float32
extracted_feat_8: shape=(259933, 191), dtype=float32
extracted_feat_None: shape=(259933, 191), dtype=float32
labels: shape=(259933,), dtype=int8
mask: shape=(259933, 200, 2), dtype=bool
mask_detection: shape=(259933, 200, 2), dtype=bool
mask_photometry: shape=(259933, 200, 2), dtype=bool
metadata_feat: shape=(259933, 8), dtype=float32
test: shape=(51682,), dtype=int64
time: shape=(259933, 200, 2), dtype=float32
time_detection: shape=

In [32]:
h5_file.get("labels")[:]

array([15., 15., 15., ...,  9.,  9.,  9.])

In [13]:
SNID = h5_file.get("extracted_feat_None")[:]
SNID

array([[          -inf, 6.20014131e-01,           -inf, ...,
        1.84868526e+01, 5.29701263e-03, 4.41670418e-01],
       [9.93605256e-01, 1.12859595e+00, 9.99999702e-01, ...,
        2.59635811e+01, 3.05970937e-01, 4.60958093e-01],
       [9.93605256e-01, 1.12859595e+00, 9.99999702e-01, ...,
        2.59635811e+01, 3.05970937e-01, 4.60958093e-01],
       ...,
       [2.68826842e-01, 2.49197841e-01, 1.00000000e+00, ...,
        1.13554443e+02, 1.50246604e-04, 1.71442255e-02],
       [2.68826842e-01, 2.49197841e-01, 1.00000000e+00, ...,
        1.13554443e+02, 1.50246604e-04, 1.71442255e-02],
       [2.68826842e-01, 2.49197841e-01, 1.00000000e+00, ...,
        1.13554443e+02, 1.50246604e-04, 1.71442255e-02]])

In [14]:
SNID[0]

array([           -inf,  6.20014131e-01,            -inf,  9.99670029e-01,
                  -inf,  2.00000000e+00,            -inf,  3.52941185e-01,
                  -inf,  0.00000000e+00, -7.35934317e-01, -5.71458578e-01,
        3.63091975e-01,            -inf,  1.41120866e-01,            -inf,
        3.17999016e-04,  4.92956006e+03,  5.22490869e+03,  2.71271973e+01,
        7.06915207e+01,            -inf, -2.37661526e-01,            -inf,
        3.20752442e-01,            -inf,  2.28584000e+08,            -inf,
        1.75457792e+08,            -inf,  1.09804152e+08,            -inf,
        5.36192080e+07,            -inf,  1.90489840e+07,            -inf,
        4.35270450e+06,            -inf,  4.77504062e+05,            -inf,
        1.85009767e-03,            -inf,  1.44261783e-02,            -inf,
        5.45665696e-02,            -inf,  1.25793442e-01,            -inf,
        2.26873726e-01,            -inf,  3.51946950e-01,            -inf,
        4.93671864e-01,  

In [ ]:
ids_unique = set([x.decode('utf-8').split('_')[0] for x in SNID])
len(ids_unique)

39701

In [6]:
ids_training_0 = list(set([x.decode('utf-8').split('_')[0] for x in SNID[h5_file.get("training_0")[:]]]))
ids_validaton_0 = list(set([x.decode('utf-8').split('_')[0] for x in SNID[h5_file.get("validation_0")[:]]]))
ids_test = list(set([x.decode('utf-8').split('_')[0] for x in SNID[h5_file.get("test")[:]]]))

In [7]:
print('ids_training_0:', len(ids_training_0))
print('ids_validaton_0:', len(ids_validaton_0))
print('ids_test:', len(ids_test))

ids_training_0: 25408
ids_validaton_0: 6353
ids_test: 7940


In [3]:
file_path = './ds_pre241209_pos250312_detff_ndetge8_sanchez_tax_20folds/dataset.h5'
h5_file   = h5py.File(file_path)
h5_file.keys()

for k in h5_file.keys():
    print('{}: {}'.format(k, h5_file[k].shape))

print()
print(h5_file.get("SNID")[:])
print()
print(h5_file.get("brightness")[:].shape)

SNID: (262638,)
brightness: (262638, 200, 2)
class_name: (262638,)
e_brightness: (262638, 200, 2)
extracted_feat_1024: (262638, 191)
extracted_feat_128: (262638, 191)
extracted_feat_16: (262638, 191)
extracted_feat_256: (262638, 191)
extracted_feat_32: (262638, 191)
extracted_feat_512: (262638, 191)
extracted_feat_64: (262638, 191)
extracted_feat_8: (262638, 191)
extracted_feat_None: (262638, 191)
labels: (262638,)
mask: (262638, 200, 2)
mask_detection: (262638, 200, 2)
mask_photometry: (262638, 200, 2)
metadata_feat: (262638, 8)
test: (52948,)
time: (262638, 200, 2)
time_detection: (262638, 200, 2)
time_photometry: (262638, 200, 2)
training_0: (167990,)
training_1: (167533,)
training_10: (167764,)
training_11: (167559,)
training_12: (167911,)
training_13: (168082,)
training_14: (167328,)
training_15: (167357,)
training_16: (168383,)
training_17: (167949,)
training_18: (168446,)
training_19: (167696,)
training_2: (167932,)
training_3: (168081,)
training_4: (168010,)
training_5: (167782


(262638, 200, 2)


In [8]:
file_path = './ds_pre241209_pos250306_detff_ndetge8_20folds/dataset.h5'
h5_file   = h5py.File(file_path)
h5_file.keys()

for k in h5_file.keys():
    print('{}: {}'.format(k, h5_file[k].shape))

print()
print(h5_file.get("SNID")[:])
print()
print(h5_file.get("brightness")[:].shape)

SNID: (262638,)
brightness: (262638, 200, 2)
class_name: (262638,)
e_brightness: (262638, 200, 2)
extracted_feat_1024: (262638, 191)
extracted_feat_128: (262638, 191)
extracted_feat_16: (262638, 191)
extracted_feat_256: (262638, 191)
extracted_feat_32: (262638, 191)
extracted_feat_512: (262638, 191)
extracted_feat_64: (262638, 191)
extracted_feat_8: (262638, 191)
extracted_feat_None: (262638, 191)
labels: (262638,)
mask: (262638, 200, 2)
mask_detection: (262638, 200, 2)
mask_photometry: (262638, 200, 2)
metadata_feat: (262638, 8)
test: (52948,)
time: (262638, 200, 2)
time_detection: (262638, 200, 2)
time_photometry: (262638, 200, 2)
training_0: (167569,)
training_1: (167913,)
training_10: (167833,)
training_11: (167739,)
training_12: (167550,)
training_13: (167489,)
training_14: (167526,)
training_15: (167600,)
training_16: (168027,)
training_17: (167895,)
training_18: (168017,)
training_19: (167283,)
training_2: (167727,)
training_3: (167560,)
training_4: (167245,)
training_5: (167830

In [4]:
print(np.unique(h5_file.get("labels")[:]))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [3]:
mask_phot = h5_file.get("mask_photometry")[:]

for i, mask_phot_sample in enumerate(mask_phot):
    has_nonzero = np.any(mask_phot_sample != 0)
    if has_nonzero:
        print(i)
        break

4


In [4]:
array = h5_file.get("time_photometry")[:][6]
np.set_printoptions(precision=4, suppress=True)
print(array.shape)
print(array)

(200, 2)
[[  0.       0.9334]
 [  1.9542   0.9744]
 [  2.8744   1.9281]
 [  3.8775   1.9745]
 [  4.0111   1.9827]
 [  4.0192   2.8445]
 [  4.8744   8.8049]
 [  5.0152   8.967 ]
 [  5.0233   9.971 ]
 [  5.8758  10.9709]
 [  6.012   17.9105]
 [  6.0201  17.9689]
 [  6.8756  17.9774]
 [  7.0129  18.8896]
 [  7.021   27.8897]
 [  7.8306  33.9698]
 [  7.9794  33.9777]
 [  8.83    34.9129]
 [  8.9756  34.9692]
 [  9.9795  34.977 ]
 [ 10.8388  70.8573]
 [ 10.9794  82.7277]
 [ 11.8306 117.7333]
 [ 12.9156 144.7121]
 [ 12.9831 148.7104]
 [ 13.9361 238.1484]
 [ 13.9844 254.1362]
 [ 14.916  263.0861]
 [ 14.9828 273.9838]
 [ 15.937  275.0835]
 [ 15.9874 275.093 ]
 [ 15.9959 275.1016]
 [ 16.9166 276.0979]
 [ 16.9869 278.1083]
 [ 16.9953 278.1092]
 [ 17.9873 279.0829]
 [ 17.9958 284.1184]
 [ 18.9164 295.0886]
 [ 19.9155 296.1144]
 [ 19.987  299.0745]
 [ 19.9954 301.9368]
 [ 20.9382 302.9397]
 [ 20.9868 307.0219]
 [ 20.9952 307.0228]
 [ 21.9382 308.9756]
 [ 21.9886 309.921 ]
 [ 21.997  311.0842]
 [ 2

In [15]:
import numpy as np

# Lista de IDs como ejemplo
ids = h5_file.get("SNID")[:]

# Convertir a string si es necesario y eliminar la parte después del guion bajo
cleaned_ids = np.array([id.split(b'_')[0] for id in ids])

# Contar los IDs únicos
unique_ids, counts = np.unique(cleaned_ids, return_counts=True)

# Mostrar el resultado
for unique_id, count in zip(unique_ids, counts):
    print(f"ID: {unique_id.decode('utf-8')} - Count: {count}")

print(f"\nTotal Unique IDs: {len(unique_ids)}")

ID: ZTF17aaaaabj - Count: 7
ID: ZTF17aaaaaej - Count: 13
ID: ZTF17aaaaafz - Count: 14
ID: ZTF17aaaaajg - Count: 14
ID: ZTF17aaaaavq - Count: 20
ID: ZTF17aaaaaya - Count: 12
ID: ZTF17aaaabbo - Count: 8
ID: ZTF17aaaabhx - Count: 14
ID: ZTF17aaaacnc - Count: 4
ID: ZTF17aaaactd - Count: 4
ID: ZTF17aaaacth - Count: 5
ID: ZTF17aaaadbq - Count: 8
ID: ZTF17aaaadmx - Count: 13
ID: ZTF17aaaaepx - Count: 6
ID: ZTF17aaaafbz - Count: 12
ID: ZTF17aaaafcd - Count: 12
ID: ZTF17aaaafdm - Count: 26
ID: ZTF17aaaagai - Count: 18
ID: ZTF17aaaaghy - Count: 7
ID: ZTF17aaaagvx - Count: 13
ID: ZTF17aaaagym - Count: 13
ID: ZTF17aaaagyq - Count: 7
ID: ZTF17aaaagyx - Count: 7
ID: ZTF17aaaahsl - Count: 15
ID: ZTF17aaaajey - Count: 22
ID: ZTF17aaaajez - Count: 22
ID: ZTF17aaaajgm - Count: 12
ID: ZTF17aaaajgo - Count: 21
ID: ZTF17aaaajhl - Count: 21
ID: ZTF17aaaajhn - Count: 29
ID: ZTF17aaaajhz - Count: 12
ID: ZTF17aaaajib - Count: 29
ID: ZTF17aaaajim - Count: 22
ID: ZTF17aaaajio - Count: 21
ID: ZTF17aaaajiy - Count

In [3]:
h5_file.get("brightness")[:]

array([[[  41.11764476,  249.19457563],
        [ -56.68440988, -293.97967023],
        [ -49.83797035, -436.42591959],
        ...,
        [   0.        ,    0.        ],
        [   0.        ,    0.        ],
        [   0.        ,    0.        ]],

       [[ -68.34535865, -372.16363883],
        [ 116.97437211,   94.25414749],
        [  66.35383096, -357.92827047],
        ...,
        [   0.        ,    0.        ],
        [   0.        ,    0.        ],
        [   0.        ,    0.        ]],

       [[ -35.67814785, -194.83215365],
        [ -50.5114881 ,  631.69025266],
        [   0.        ,  605.00172557],
        ...,
        [   0.        ,  714.05943696],
        [   0.        ,    0.        ],
        [   0.        ,    0.        ]],

       ...,

       [[  -1.11255639,  -16.27532594],
        [   1.22770024,   47.64353254],
        [   8.61049517,   58.8185814 ],
        ...,
        [   0.        ,    0.        ],
        [   0.        ,    0.        ],
        [

In [4]:
mask_phot = h5_file.get("mask_photometry")[:]

for i, mask_phot_sample in enumerate(mask_phot):
    has_nonzero = np.any(mask_phot_sample != 0)
    if has_nonzero:
        print(i)
        break


6


In [5]:
array = h5_file.get("time_photometry")[:][6]
np.set_printoptions(precision=4, suppress=True)
print(array.shape)
print(array)

(200, 2)
[[  0.       9.0612]
 [  8.974   13.9987]
 [ 27.9821 119.8481]
 [ 31.0664 121.9123]
 [ 44.0441 125.8345]
 [ 46.9849 149.8123]
 [ 69.055  156.9254]
 [ 70.8519 163.8822]
 [ 71.9777 171.6903]
 [ 73.9502 242.7569]
 [106.9776 434.0431]
 [109.9582 482.8305]
 [111.8792 502.8378]
 [114.9784 503.8613]
 [121.9351 511.7768]
 [123.9818 512.7268]
 [133.9804 512.7984]
 [149.8636 512.7993]
 [152.7585 512.8842]
 [154.6876 707.0439]
 [166.7236 707.0488]
 [175.7656 744.9669]
 [188.7547 772.0044]
 [217.7305 809.9184]
 [223.713  811.0381]
 [239.7032 829.9574]
 [245.749  880.7928]
 [364.062  945.7129]
 [374.0411 959.7194]
 [447.9663   0.    ]
 [451.0489   0.    ]
 [455.9219   0.    ]
 [479.8104   0.    ]
 [479.8213   0.    ]
 [479.8521   0.    ]
 [479.8531   0.    ]
 [485.7749   0.    ]
 [485.7758   0.    ]
 [487.7736   0.    ]
 [487.7745   0.    ]
 [511.6858   0.    ]
 [511.6867   0.    ]
 [517.7935   0.    ]
 [542.6914   0.    ]
 [545.7081   0.    ]
 [550.727    0.    ]
 [567.6915   0.    ]
 [56

In [6]:
time_detection = h5_file.get("time_detection")[:][6]
np.set_printoptions(precision=4, suppress=True)
print(time_detection.shape)
print(time_detection)

(200, 2)
[[ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.      -0.    ]
 [ -0.       0.0384]
 [ -0.       4.0382]
 [ -0.       8.0135]
 [ -0.      10.9713]
 [ -0.      13.0256]
 [ -0.      16.0137]
 [ -0.      30.976 ]
 [ -0.      37.0592]
 [ -0.      54.0456]
 [ -0.      69.9042]
 [ -0.      74.9744]
 [ -0.     118.9689]
 [ -0.     218.2266]
 [ -0.     218.2291]
 [ -0.     218.2315]
 [ -0.     218.2339]
 [ -0.     219.2253]
 [ -0.     219.2277]
 [ -

In [7]:
time = h5_file.get("time")[:][6]
np.set_printoptions(precision=4, suppress=True)
print(time.shape)
print(time)

(200, 2)
[[   0.        9.0612]
 [   8.974    13.9987]
 [  27.9821  119.8481]
 [  31.0664  121.9123]
 [  44.0441  125.8345]
 [  46.9849  149.8123]
 [  69.055   156.9254]
 [  70.8519  163.8822]
 [  71.9777  171.6903]
 [  73.9502  242.7569]
 [ 106.9776  434.0431]
 [ 109.9582  482.8305]
 [ 111.8792  502.8378]
 [ 114.9784  503.8613]
 [ 121.9351  511.7768]
 [ 123.9818  512.7268]
 [ 133.9804  512.7984]
 [ 149.8636  512.7993]
 [ 152.7585  512.8842]
 [ 154.6876  707.0439]
 [ 166.7236  707.0488]
 [ 175.7656  744.9669]
 [ 188.7547  772.0044]
 [ 217.7305  809.9184]
 [ 223.713   811.0381]
 [ 239.7032  829.9574]
 [ 245.749   880.7928]
 [ 364.062   945.7129]
 [ 374.0411  959.7194]
 [ 447.9663 1580.8573]
 [ 451.0489 1584.8571]
 [ 455.9219 1588.8325]
 [ 479.8104 1591.7902]
 [ 479.8213 1593.8445]
 [ 479.8521 1596.8326]
 [ 479.8531 1611.7949]
 [ 485.7749 1617.8781]
 [ 485.7758 1634.8645]
 [ 487.7736 1650.7231]
 [ 487.7745 1655.7933]
 [ 511.6858 1699.7878]
 [ 511.6867 1799.0455]
 [ 517.7935 1799.048 ]
 [

In [8]:
mask_det = h5_file.get("mask_detection")[:][6]
np.set_printoptions(precision=4, suppress=True)
print(mask_det.shape)
print(mask_det)

(200, 2)
[[False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 

In [9]:
mask = h5_file.get("mask")[:][6]
np.set_printoptions(precision=4, suppress=True)
print(mask.shape)
print(mask)

(200, 2)
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 

In [10]:
mask_time = time_detection <= 16
print(f'a:\n{mask_time}')

a:
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True

In [11]:
print(f'a:\n{mask * mask_time}')

a:
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True

In [12]:
file_path = './ds_pre241015_pos250115_detff/dataset.h5'
h5_file   = h5py.File(file_path)
h5_file.keys()

for k in h5_file.keys():
    print('{}: {}'.format(k, h5_file[k].shape))

print()
print(h5_file.get("SNID")[:])
print()
print(h5_file.get("brightness")[:].shape)

SNID: (276450,)
brightness: (276450, 200, 2)
class_name: (276450,)
e_brightness: (276450, 200, 2)
extracted_feat_1024: (276450, 191)
extracted_feat_128: (276450, 191)
extracted_feat_16: (276450, 191)
extracted_feat_256: (276450, 191)
extracted_feat_32: (276450, 191)
extracted_feat_512: (276450, 191)
extracted_feat_64: (276450, 191)
extracted_feat_None: (276450, 191)
labels: (276450,)
mask: (276450, 200, 2)
mask_detection: (276450, 200, 2)
mask_photometry: (276450, 200, 2)
metadata_feat: (276450, 8)
test: (55739,)
time: (276450, 200, 2)
time_detection: (276450, 200, 2)
time_photometry: (276450, 200, 2)
training_0: (176122,)
training_1: (177053,)
training_2: (176507,)
training_3: (176444,)
training_4: (176718,)
validation_0: (44589,)
validation_1: (43658,)
validation_2: (44204,)
validation_3: (44267,)
validation_4: (43993,)

[b'ZTF19aanbojt_0' b'ZTF19aanbojt_1' b'ZTF19aanjjhk_0' ...
 b'ZTF18abeibep_14' b'ZTF18abeibep_15' b'ZTF18abeibep_16']

(276450, 200, 2)


In [13]:
import numpy as np

# Lista de IDs como ejemplo
ids = h5_file.get("SNID")[:]

# Convertir a string si es necesario y eliminar la parte después del guion bajo
cleaned_ids = np.array([id.split(b'_')[0] for id in ids])

# Contar los IDs únicos
unique_ids, counts = np.unique(cleaned_ids, return_counts=True)

# Mostrar el resultado
for unique_id, count in zip(unique_ids, counts):
    print(f"ID: {unique_id.decode('utf-8')} - Count: {count}")

print(f"\nTotal Unique IDs: {len(unique_ids)}")

ID: ZTF17aaaaabj - Count: 7
ID: ZTF17aaaaaej - Count: 13
ID: ZTF17aaaaafz - Count: 14
ID: ZTF17aaaaajg - Count: 14
ID: ZTF17aaaaavq - Count: 20
ID: ZTF17aaaaaya - Count: 20
ID: ZTF17aaaabbo - Count: 8
ID: ZTF17aaaabhx - Count: 15
ID: ZTF17aaaacnc - Count: 4
ID: ZTF17aaaactd - Count: 4
ID: ZTF17aaaacth - Count: 5
ID: ZTF17aaaadbq - Count: 8
ID: ZTF17aaaadmx - Count: 13
ID: ZTF17aaaaepx - Count: 6
ID: ZTF17aaaafbz - Count: 20
ID: ZTF17aaaafcd - Count: 12
ID: ZTF17aaaafdm - Count: 27
ID: ZTF17aaaagai - Count: 18
ID: ZTF17aaaaghy - Count: 9
ID: ZTF17aaaagvx - Count: 13
ID: ZTF17aaaagym - Count: 13
ID: ZTF17aaaagyq - Count: 7
ID: ZTF17aaaagyx - Count: 7
ID: ZTF17aaaahsl - Count: 15
ID: ZTF17aaaajey - Count: 22
ID: ZTF17aaaajez - Count: 22
ID: ZTF17aaaajgm - Count: 12
ID: ZTF17aaaajgo - Count: 21
ID: ZTF17aaaajhl - Count: 25
ID: ZTF17aaaajhn - Count: 29
ID: ZTF17aaaajhz - Count: 12
ID: ZTF17aaaajib - Count: 29
ID: ZTF17aaaajim - Count: 22
ID: ZTF17aaaajio - Count: 21
ID: ZTF17aaaajiy - Count

In [15]:
file_path = './ds_pre241209_pos250109_detff_to_eval_ndetcutNone/dataset.h5'
h5_file   = h5py.File(file_path)
h5_file.keys()

for k in h5_file.keys():
    print('{}: {}'.format(k, h5_file[k].shape))

print()
print(h5_file.get("SNID")[:])
print()
print(h5_file.get("brightness")[:].shape)

SNID: (263773,)
brightness: (263773, 200, 2)
class_name: (263773,)
e_brightness: (263773, 200, 2)
extracted_feat_None: (263773, 191)
labels: (263773,)
mask: (263773, 200, 2)
mask_detection: (263773, 200, 2)
mask_photometry: (263773, 200, 2)
metadata_feat: (263773, 8)
test: (53174,)
time: (263773, 200, 2)
time_detection: (263773, 200, 2)
time_photometry: (263773, 200, 2)
training_0: (167999,)
training_1: (168837,)
training_2: (168395,)
training_3: (168434,)
training_4: (168731,)
validation_0: (42600,)
validation_1: (41762,)
validation_2: (42204,)
validation_3: (42165,)
validation_4: (41868,)

[b'ZTF18abklbam_0' b'ZTF18abmqupd_0' b'ZTF18abmqupd_1' ...
 b'ZTF18abeibep_14' b'ZTF18abeibep_15' b'ZTF18abeibep_16']



(263773, 200, 2)


In [17]:
h5_file.get("brightness")[:]

array([[[   0.1273,    2.3377],
        [   0.5805,   -2.4234],
        [   1.6819,   -0.5468],
        ...,
        [   0.    ,    0.    ],
        [   0.    ,    0.    ],
        [   0.    ,    0.    ]],

       [[ -25.6907,  -76.5988],
        [ -22.2226,  -83.9384],
        [ -52.0979, -114.3901],
        ...,
        [   0.    ,    0.    ],
        [   0.    ,    0.    ],
        [   0.    ,    0.    ]],

       [[ -96.1745, -277.7642],
        [ -80.8906, -278.4743],
        [ -94.3741, -274.2681],
        ...,
        [   0.    ,    0.    ],
        [   0.    ,    0.    ],
        [   0.    ,    0.    ]],

       ...,

       [[  34.0388,   70.8696],
        [ -42.6302,   90.8404],
        [ -57.7955,   91.1607],
        ...,
        [   0.    ,    0.    ],
        [   0.    ,    0.    ],
        [   0.    ,    0.    ]],

       [[ -64.2232,   96.2377],
        [ -83.5882,   71.9561],
        [ -40.3563,   96.9282],
        ...,
        [   0.    ,    0.    ],
        [   0.    

In [5]:
file_path = './dataset_pre241209_pos241229/dataset.h5'
h5_file   = h5py.File(file_path)
h5_file.keys()

for k in h5_file.keys():
    print('{}: {}'.format(k, h5_file[k].shape))

print()
print(h5_file.get("SNID")[:])
print()
print(h5_file.get("brightness")[:].shape)

FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = './dataset_pre241209_pos241229/dataset.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [11]:
# Filtrar valores cuyo sufijo (después del guión bajo '_') es distinto de 0
filtered_values = [value for value in h5_file.get("SNID")[:] if int(value.split(b'_')[-1]) != 0]

# Mostrar los resultados
print(f"Numero de valores con mas de una ventana: {len(filtered_values)}")
print(filtered_values)

Numero de valores con mas de una ventana: 430
[b'ZTF18aagrlln_1', b'ZTF18aagrmyu_1', b'ZTF18aagrsfa_1', b'ZTF18aagteil_1', b'ZTF18aagteim_1', b'ZTF18aagteqi_1', b'ZTF18aagtgjh_1', b'ZTF18aaguzxn_1', b'ZTF18aagxbun_1', b'ZTF18aahcgqv_1', b'ZTF18aaijuyb_1', b'ZTF18aaimxms_1', b'ZTF18aainbqt_1', b'ZTF18aaioqrj_1', b'ZTF18aaiylnn_1', b'ZTF18aajdkni_1', b'ZTF18aakhend_1', b'ZTF18aakhgms_1', b'ZTF18aakxqyk_1', b'ZTF18aammumc_1', b'ZTF18aapyvah_1', b'ZTF18aabejps_1', b'ZTF18aabtugc_1', b'ZTF18aagrgky_1', b'ZTF18aagrhaz_1', b'ZTF18aagriwp_1', b'ZTF18aagrrar_1', b'ZTF18aaijvcd_1', b'ZTF18aaixfkb_1', b'ZTF18aaiyvdn_1', b'ZTF18aajrouw_1', b'ZTF18aagrefk_1', b'ZTF18aagxdck_1', b'ZTF18aagxtxq_1', b'ZTF18aaiugdp_1', b'ZTF18aajtfjw_1', b'ZTF18aalscdp_1', b'ZTF18aammumv_1', b'ZTF18aaoechc_1', b'ZTF18aaptcpp_1', b'ZTF18aacgqfy_1', b'ZTF18aagrhbf_1', b'ZTF18aaiwnoj_1', b'ZTF18aajucng_1', b'ZTF17aabvcqg_1', b'ZTF18aagrcaw_1', b'ZTF18aagrchd_1', b'ZTF18aagrggq_1', b'ZTF18aagrgrd_1', b'ZTF18aagrhuj_1', b'Z

In [17]:
h5_file.get("mask_photometry")[:]

array([[[False, False],
        [False, False],
        [False, False],
        ...,
        [False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        ...,
        [False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        ...,
        [False, False],
        [False, False],
        [False, False]],

       ...,

       [[False, False],
        [False, False],
        [False, False],
        ...,
        [False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        ...,
        [False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        ...,
        [False, False],
        [False, False],
        [False, False]]])

In [12]:
import numpy as np
import pandas as pd

# Reorganizar el array para obtener flujos y bandas en formato 2D
flux = h5_file.get("extracted_feat_None")[:].reshape(-1, 2)  # Combinar las dos primeras dimensiones (flujos)
bands = np.tile([1, 2], flux.shape[0] // 2)  # Crear una "columna" de bandas (1 y 2)

# Crear una función para calcular estadísticas por grupo (banda)
def calculate_group_stats(flux, bands):
    unique_bands = np.unique(bands)
    stats = []
    for band in unique_bands:
        band_flux = flux[bands == band]
        stats.append({
            "fid": band,
            "Mean": round(np.mean(band_flux), 4),
            "Std": round(np.std(band_flux), 4),
            "Min": round(np.min(band_flux), 4),
            "P25": round(np.percentile(band_flux, 25), 4),
            "Median": round(np.median(band_flux), 4),
            "P75": round(np.percentile(band_flux, 75), 4),
            "Max": round(np.max(band_flux), 4),
        })
    return pd.DataFrame(stats)

# Calcular estadísticas
stats_df = calculate_group_stats(flux, bands)
print(stats_df)

/home/dmoreno/.virtualenvs/ATAT_ALeRCE/lib/python3.10/site-packages/numpy/core/_methods.py:173: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)


   fid  Mean  Std  Min     P25  Median     P75           Max
0    1  -inf  NaN -inf  0.0063   0.322  3.8359  6.600653e+13
1    2  -inf  NaN -inf  0.0063   0.322  3.8393  4.514512e+13


In [9]:
these_idx =  h5_file.get("test")[:]
these_idx

array([     6,      7,      8, ..., 215597, 215598, 215599])

In [10]:
import numpy as np
np.sum(h5_file.get("class_name")[:][these_idx] == b'Periodic-Other')

554

In [6]:
lcid = h5_file['SNID'][these_idx]
len(lcid)

58084

In [7]:
lcids_po_tp = lcid[h5_file.get("class_name")[:][these_idx] == b'Periodic-Other']
lcids_po_tp

array([b'ZTF18acrxopg_0', b'ZTF18acrxopg_1', b'ZTF18acrxopg_2',
       b'ZTF18acsjcqz_0', b'ZTF18acsjcqz_1', b'ZTF18acsjcqz_2',
       b'ZTF18acsjcqz_3', b'ZTF18acsjcqz_4', b'ZTF18acsjcqz_5',
       b'ZTF18actwwmx_0', b'ZTF18actwwmx_1', b'ZTF18acvllel_0',
       b'ZTF18aczcgyr_0', b'ZTF18aczcgyr_1', b'ZTF18aczcgyr_2',
       b'ZTF18aczcgyr_3', b'ZTF18aczcgyr_4', b'ZTF18aczcgyr_5',
       b'ZTF18aczcgyr_6', b'ZTF18adiutsk_0', b'ZTF19aaakswo_0',
       b'ZTF19aaakswo_1', b'ZTF19aabhxug_0', b'ZTF19aabhxug_1',
       b'ZTF19aabhxug_2', b'ZTF19aabhxug_3', b'ZTF19aaeduba_0',
       b'ZTF19aaesjny_0', b'ZTF19aaetodq_0', b'ZTF19aaetodq_1',
       b'ZTF19aamgbym_0', b'ZTF19aamgbym_1', b'ZTF19aamgbym_2',
       b'ZTF19aamttoa_0', b'ZTF19aamttoa_1', b'ZTF19aanwcyb_0',
       b'ZTF19aanwcyb_1', b'ZTF19aapzvnq_0', b'ZTF19aapzvnq_1',
       b'ZTF19aaradmv_0', b'ZTF19aaradmv_1', b'ZTF19aarfewb_0',
       b'ZTF19aasqiml_0', b'ZTF19aasqiml_1', b'ZTF19aatrfaq_0',
       b'ZTF19aatrfaq_1', b'ZTF19aatrfaw

In [8]:
training_po_oids = list(set([oid.split(b'_')[0].decode('utf-8') for oid in lcids_po_tp]))
training_po_oids

['ZTF17aaajeyp',
 'ZTF19aaxlibg',
 'ZTF18aczbyew',
 'ZTF22aahydwv',
 'ZTF18aaeasks',
 'ZTF19aacolve',
 'ZTF19aabfsfa',
 'ZTF23abjhwrb',
 'ZTF18abmvgvp',
 'ZTF19aaezopp',
 'ZTF19aasqiml',
 'ZTF19aaacdes',
 'ZTF19adhshej',
 'ZTF19aaxjwyg',
 'ZTF18acwgbdk',
 'ZTF23aahrvkj',
 'ZTF19adddghr',
 'ZTF20aanzlrc',
 'ZTF21acqheka',
 'ZTF18abnttfy',
 'ZTF18aauxodi',
 'ZTF18aabasqj',
 'ZTF18acvsajv',
 'ZTF21abfaxsq',
 'ZTF20acwpfzy',
 'ZTF19aapzvnq',
 'ZTF22aabwzyi',
 'ZTF22aaevncu',
 'ZTF21aalsjpt',
 'ZTF21aabgpvw',
 'ZTF19aaxlipg',
 'ZTF22abqpaew',
 'ZTF21abjxrpq',
 'ZTF21aamjgdf',
 'ZTF19aaetodq',
 'ZTF19abqwyka',
 'ZTF21aamqmvo',
 'ZTF20aczghhj',
 'ZTF17aaaztas',
 'ZTF19addfhjz',
 'ZTF18aapjmux',
 'ZTF18aaghcdq',
 'ZTF19aaysucv',
 'ZTF18abwmwck',
 'ZTF19aatrfaw',
 'ZTF19abbzcsz',
 'ZTF19aaxliix',
 'ZTF19aayjqxi',
 'ZTF19abohyfq',
 'ZTF22aaeecuq',
 'ZTF22aahbfyh',
 'ZTF17aabwosf',
 'ZTF18abwecon',
 'ZTF19abdylab',
 'ZTF23aamapva',
 'ZTF18acqwunb',
 'ZTF19aayhrte',
 'ZTF19aaxljhm',
 'ZTF18abafbtf

In [9]:
len(training_po_oids)

264

In [10]:
h5_file.get("flux")[:][these_idx][0][0]

array([-6.98710327, 57.24037793])

In [11]:
h5_file.get("flux")[:].shape

(291375, 200, 2)

In [12]:
h5_file.get("flux")[:][:, :, 0].shape

(291375, 200)

In [13]:
h5_file['SNID'][these_idx]

array([b'ZTF17aacwfbp_0', b'ZTF17aacwfbp_1', b'ZTF17aacwfbp_2', ...,
       b'ZTF19aamnvfx_3', b'ZTF19aamnvfx_4', b'ZTF19aamnvfx_5'],
      dtype=object)

In [14]:
file_path = './LC_MD_FEAT_241209_windows_200_12/dataset.h5'
h5_file   = h5py.File(file_path)
h5_file.keys()

for k in h5_file.keys():
    print('{}: {}'.format(k, h5_file[k].shape))

SNID: (288954,)
class_name: (288954,)
extracted_feat_1024: (288954, 191)
extracted_feat_128: (288954, 191)
extracted_feat_16: (288954, 191)
extracted_feat_2048: (288954, 191)
extracted_feat_256: (288954, 191)
extracted_feat_32: (288954, 191)
extracted_feat_512: (288954, 191)
extracted_feat_64: (288954, 191)
extracted_feat_8: (288954, 191)
flux: (288954, 200, 2)
flux_err: (288954, 200, 2)
labels: (288954,)
mask: (288954, 200, 2)
mask_detection: (288954, 200, 2)
mask_photometry: (288954, 200, 2)
metadata_feat: (288954, 8)
test: (57722,)
time: (288954, 200, 2)
time_detection: (288954, 200, 2)
time_photometry: (288954, 200, 2)
training_0: (185173,)
training_1: (185250,)
training_2: (184787,)
training_3: (184471,)
training_4: (185247,)
validation_0: (46059,)
validation_1: (45982,)
validation_2: (46445,)
validation_3: (46761,)
validation_4: (45985,)


In [8]:
h5_file.get("brightness")[:]

array([[[  81.06877257,   67.82297676],
        [ 141.89559738,  173.41414365],
        [ 120.645269  ,  176.24047663],
        ...,
        [   0.        ,    0.        ],
        [   0.        ,    0.        ],
        [   0.        ,    0.        ]],

       [[  95.63777836,  265.58638361],
        [ 188.58279032,  150.5006263 ],
        [ -33.09778309,  404.1265265 ],
        ...,
        [   0.        ,    0.        ],
        [   0.        ,    0.        ],
        [   0.        ,    0.        ]],

       [[-216.11957906, -156.83286304],
        [-222.66079119, -106.36827478],
        [-186.37988839,   46.07074049],
        ...,
        [   0.        ,    0.        ],
        [   0.        ,    0.        ],
        [   0.        ,    0.        ]],

       ...,

       [[  57.32878153,  108.79206562],
        [ -29.8770264 ,   38.56629538],
        [ -62.12201719,   70.86960026],
        ...,
        [   0.        ,    0.        ],
        [   0.        ,    0.        ],
        [

   fid     Mean        Std           Min  P25  Median  P75           Max
0    1  29.1105  2094.8298 -5.301212e+04  0.0     0.0  0.0  1.592556e+06
1    2  28.7954  2115.5976 -2.136146e+06  0.0     0.0  0.0  1.605385e+06
